server:
  port: 80
  servlet:
    context-path: /girl
cupSize: D
age: 18
content: "cupSize:${cupSize},age:${age}"
boy:
  height: 180cm
  weight: 50kg
jdbc.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
jdbc.username: root
jdbc.password: 1qaz2wsx
jdbc.driver: com.mysql.jdbc.Driver
mybatis_config_file: mybaits-config.xml
mapper_path: /daoMapper/**.xml
entity_package: com.sdw.entity